/******************************************************************************/
/****        Generated by IBExpert 2015.12.21.1 14/07/2022 21:46:49        ****/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES NONE;

SET CLIENTLIB 'C:\Program Files (x86)\Firebird\Firebird_3_0\fbclient.dll';

CREATE DATABASE 'C:\Projetos\Controle de Caixa\Dados\Caixa.fdb'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 16384
DEFAULT CHARACTER SET NONE COLLATION NONE;



/******************************************************************************/
/****                              Generators                              ****/
/******************************************************************************/

CREATE GENERATOR GEN_EMPRESA_ID START WITH 0 INCREMENT BY 1;
SET GENERATOR GEN_EMPRESA_ID TO 0;

CREATE GENERATOR GEN_FLUXO_CAIXA_ID START WITH 0 INCREMENT BY 1;
SET GENERATOR GEN_FLUXO_CAIXA_ID TO 0;

CREATE GENERATOR GEN_PLANO_CONTAS_ID START WITH 0 INCREMENT BY 1;
SET GENERATOR GEN_PLANO_CONTAS_ID TO 0;



/******************************************************************************/
/****                                Tables                                ****/
/******************************************************************************/



CREATE TABLE EMPRESA (
    ID_EMPRESA     BIGINT NOT NULL,
    RAZAO_SOCIAL   VARCHAR(50) NOT NULL,
    NOME_FANTASIA  VARCHAR(50) NOT NULL
);

CREATE TABLE FLUXO_CAIXA (
    ID_CAIXA        BIGINT NOT NULL,
    DATA            DATE NOT NULL,
    HORA            TIME NOT NULL,
    ID_PLANO        BIGINT NOT NULL,
    DESCRICAO_LANC  VARCHAR(255) NOT NULL,
    VALOR           NUMERIC(15,2) NOT NULL,
    ID_EMPRESA      BIGINT NOT NULL
);

CREATE TABLE PLANO_CONTAS (
    ID_PLANO  BIGINT NOT NULL,
    PLANO     VARCHAR(50) NOT NULL,
    TIPO      SMALLINT DEFAULT 0 NOT NULL
);



/******************************************************************************/
/****                             Primary keys                             ****/
/******************************************************************************/

ALTER TABLE EMPRESA ADD CONSTRAINT PK_EMPRESA PRIMARY KEY (ID_EMPRESA);
ALTER TABLE FLUXO_CAIXA ADD CONSTRAINT PK_FLUXO_CAIXA PRIMARY KEY (ID_CAIXA);
ALTER TABLE PLANO_CONTAS ADD CONSTRAINT PK_PLANO_CONTAS PRIMARY KEY (ID_PLANO);


/******************************************************************************/
/****                             Foreign keys                             ****/
/******************************************************************************/

ALTER TABLE FLUXO_CAIXA ADD CONSTRAINT FK_FLUXO_CAIXA_1 FOREIGN KEY (ID_PLANO) REFERENCES PLANO_CONTAS (ID_PLANO);
ALTER TABLE FLUXO_CAIXA ADD CONSTRAINT FK_FLUXO_CAIXA_2 FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESA (ID_EMPRESA);


/******************************************************************************/
/****                               Triggers                               ****/
/******************************************************************************/



SET TERM ^ ;



/******************************************************************************/
/****                         Triggers for tables                          ****/
/******************************************************************************/



/* Trigger: EMPRESA_BI */
CREATE TRIGGER EMPRESA_BI FOR EMPRESA
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id_empresa is null) then
    new.id_empresa = gen_id(gen_empresa_id,1);
end
^

/* Trigger: FLUXO_CAIXA_BI */
CREATE TRIGGER FLUXO_CAIXA_BI FOR FLUXO_CAIXA
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id_caixa is null) then
    new.id_caixa = gen_id(gen_fluxo_caixa_id,1);
end
^

/* Trigger: PLANO_CONTAS_BI */
CREATE TRIGGER PLANO_CONTAS_BI FOR PLANO_CONTAS
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id_plano is null) then
    new.id_plano = gen_id(gen_plano_contas_id,1);
end
^
SET TERM ; ^

